### ISSUE TITLE
When fetching wishes you make an extra unnecessary request.

### ISSUE THREAD

**Issue by ashleney** [MadeBaruna/paimon-moe-api#1]
This is just a little pet peeve of mine, but when getting the pages you seem to check for an empty list instead of checking whether the list length is lower than 20.

Normally I'd make a pr but typescript isn't my strong suit so I'm sorry if this just happens to be a little thing you didn't have time to worry about.

**Comment by MadeBaruna** [comment]
I need to make the last request, because if the last page is exactly 20 items, you can't really sure if that is the last page
