### ISSUE TITLE
Error running on raspberry pi, docker-entrypoint.sh failed on arm64

### ISSUE THREAD

**Issue by jackthenewbie** [MadeBaruna/paimon-moe-api#5]
running this on raspberry pi, the other 2 containers are postgres and redis is running fine. But image ``ghcr.io/madebaruna/paimon-moe-api:latest`` keep restarting, when I check logs, it only show this

> [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (8)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (6)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (9)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (6)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error
> [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error

been trying to google awhile, but couldn't figure it out. help me pls?:)

**Comment by MadeBaruna** [comment]
Hmm I'm not sure, maybe the image doesn't support arm?

**Comment by jackthenewbie** [comment]
> Hmm I'm not sure, maybe the image doesn't support arm?

umm not really sure, in dockerfile you use [node:14.19.3-alpine3.14](https://hub.docker.com/layers/node/library/node/14.19.3-alpine3.14/images/sha256-aaff8d3ee1eb455319df87891025c0a17324788d2d58f206e8f7574160f85ada?context=explore) right? I thought they support arm here? or do I have to specify which arch im using in dockerfile?

**Comment by MadeBaruna** [comment]
Well sorry I never use raspi with docker, you need to explore the option yourself

**Comment by jackthenewbie** [comment]
I'm noob with docker so totally didn't know i have to rebuild the whole image then change ``image: `` in docker-compose.yml

> FROM --platform=linux/arm64/v8 node:14.19.3-alpine3.14 AS builder
WORKDIR /api
RUN apk add --no-cache python3 make g++
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --shamefully-hoist=true
COPY tsconfig.json .
COPY src src
RUN pnpm run build
RUN pnpm prune --prod

>FROM --platform=linux/arm64/v8 node:14.19.3-alpine3.14
WORKDIR /api
COPY ormconfig.js .
COPY --from=builder /api/node_modules node_modules
COPY --from=builder /api/build .
EXPOSE 3001
CMD ["node","index.js"]

welp, thanks for reading my issue regardless:)
